Repository AyushSharma72/Skill_Trade, pull requests merged in 2025-07, with the labels that each got.

#16 Logout modal enhacement
  .gitignore
  app/_components/NavBarComponenets/LogoutModal.jsx
Labels: gssoc25, level1

#19 added redirect from logo to home page
  app/_components/Navbar.jsx
Labels: gssoc25, level1

#20 Created Custom 404 Page Aligned with Site Theme Closes
  app/_components/NavBarComponenets/AdminMenu.jsx
  app/_components/NavBarComponenets/WorkerMenu.jsx
  app/not-found.jsx
  package-lock.json
  package.json
  public/404.svg
Labels: gssoc25, level1

#31 Add License and Update README
  LICENSE
  README.md
Labels: enhancement, level2

#38 feat: optimize infinite scrolling marquee for celebration gallery and…
  app/_components/MarqeeImage.jsx
  app/page.js
  next.config.mjs
Labels: gssoc25, level2

#43 Implement email templates for user inquiries and auto-replies
  server/controllers/UserController.js
Labels: enhancement, gssoc25, level2

#53 Enhanced UI of contact page
  app/Contact/page.jsx
  public/contactpg.svg
Labels: good first issue, gssoc25, level2

#64 OTP Dialog modal UI Updated
  app/user/User_Profile/_Userinfo/Userinfo.jsx
Labels: gssoc25, level3

#72 Password Validation
  app/_components/register/UserRegisterForm.jsx
  app/_components/register/WorkerRegisterForm.jsx
  package-lock.json
  package.json
Labels: gssoc25, level1

#80 Added CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: gssoc25, level1

#86 Fix footer
  app/_components/Footer.jsx
Labels: gssoc25, level1
